apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-2
  labels:
    app: web-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-2
  template:
    metadata:
      labels:
        app: web-app-2
    spec:
      containers:
      - name: web-app-2
        image: wil42/playground:v1
        ports:
        - containerPort: 8888