apiVersion: v1
kind: Service
metadata:
  name: web-app-2-service
spec:
  selector:
    app: web-app-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
