apiVersion: v1
kind: Service
metadata:
  name: web-app-3-service
spec:
  selector:
    app: web-app-3
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
